### PR TITLE
Remove redundant files

### PR DESCRIPTION
**Pull request by woutermont**
This PR removes some redundant files from the repo. As far as I know, these files do not contain relevant content, and they are not used by or refered to from any other file in the repo. Also keep in mind that this is a git repo, and so these files are not lost; if need be, we can easily restore them.

- `.default-acl`: No idea what this is. It is not even a real ACL file. Maybe @ericprud knows.
- `diff-20111123.html`: Some very old HTML file, probably meant as a diff to or from the draft back then (which is stored in the drafts folder). It's not a real diff file though, and its formatting is completely messed up, so comparing is not possible.
- `style.css` & `W3C-ED.css`: Both are (old) copies from the ReSpec and W3C stylesheets. All HTML files in the repo (even the drafts) use their online version though (or embeded CSS).

### CODE REVIEW

**Comment by melvincarvalho** [comment]
Good idea, thanks.  They all look defunct.

**Comment by jacoscaz** [comment]
_/chair hat off_

+1 from me

**Comment by jacoscaz** [comment]
Any objection to this PR?

**Comment by jacoscaz** [comment]
Any objection to this PR? Just making sure...

**Comment by jacoscaz** [comment]
Thank you @woutermont !

**Pull request merged**
