### PR TITLE
Add Note for recognising properties equivalent to foaf:primaryTopic

### PR DESCRIPTION
**Pull request by csarven**
This PR is a https://www.w3.org/2023/Process-20230612/#class-2 change towards addressing https://github.com/w3c/WebID/issues/24

### CODE REVIEW

**Review by kidehen — CHANGES_REQUESTED** [review]
<div class="note"><div class="note-title" id="h_note_3"><span>Note</span></div><p>
Implementations that recognise related properties from different vocabularies as being equivalent to <code>foaf:primaryTopic</code> are encouraged to do so in their respective WebID Profile Documents, along the same lines described in this document.</p>
</p></div>

**Comment by melvincarvalho** [comment]
IMHO this is a major work item that affects test suites.  You would need to gain consensus with the group on:

1. How substantive the change is
2. Whether to take it on as a work item
3. When to prioritize it (superset spec should come first)
4. The exact set of equivalences

I dont think we should take this on, at this time, in this order.  Once superset is done, and not before that.  The relation between a WebID and a profile document can be established.

**Comment by kidehen** [comment]
> IMHO this is a major work item that affects test suites.

I don't believe so.

We have a bigger problem right now, and it takes the form of:
What exactly is a WebID, and what is supposed to be in the WebID Spec.

We are having circular debates as a result of the above. 
A WebID is the basic foundation, in the form of an identifier type, used for unambiguous Agent naming that serves the needs of Profile Documents and Authentication Protocols. 

A WebID is neither a Profile Document nor an Authentication Protocol. It is an identifier type. The "WebID Identity and Discovery Specification" is a confusing title that attempts acronym recursion in a manner that's backfired --- IMHO.

**Comment by csarven** [comment]
>IMHO this is a major work item that affects test suites.

This change is not a "work item". This is a Note. A non-normative (informative) addition towards addressing the referenced issue.

Which test suites? Are you working on test suites?

>You would need to gain consensus with the group on:

>    How substantive the change is

This PR adds a Note. It is a non-normative (informative) addition. Here is one explanation from the W3C Manual of Style https://w3c.github.io/manual-of-style/#N-I-sections "notes are assumed to always be informative".

The initial comment https://github.com/w3c/WebID/pull/32#issue-2062776903 refers to W3C Process's correction classes ( https://www.w3.org/2023/Process-20230612/#class-2 ) which is a as a guide to help the reviewers assess the proposed change in this PR. And I quote: the "Changes that do not functionally affect interpretation of the document". More details at the referenced link.

That's "how" substantive the change is.

>    Whether to take it on as a work item

It is not proposed as a "work item". It is proposed a change to the current WebID 1.0 ED, which has been a "work item" of the WebID CG.

If you are interested in what constitutes "work item" and how to approach it the Group, here is the CONTRIBUTING proposal that includes a section on work items: https://github.com/w3c/WebID/pull/31 .

>    When to prioritize it (superset spec should come first)

Thanks for sharing an answer to your own question.

>    The exact set of equivalences

No, the proposed text does not suggest that requirement. Furthermore, any equivalences that could be made based on existing vocabulary definitions are not part of WebID CG's "work items", and hence they are out of scope here.

>I dont think we should take this on, at this time, in this order. Once superset is done, and not before that. The relation between a WebID and a profile document can be established.

Thank you for your comment.

**Review by kidehen — APPROVED** [review]
That works.

**Comment by melvincarvalho** [comment]
To clarify.  Hard NACK.  Please gain consensus of the chair and group.

**Comment by melvincarvalho** [comment]
> Thanks for sharing an answer to your own question.

@csarven this is completely inappropriate

**Comment by kidehen** [comment]
> To clarify. Hard NACK. Please gain consensus of the chair and group.

I don't understand your comment above. I am simply acknowledging what @csarven has contributed. Basically, going beyond a thumbs-up or thumbs-down. 

BTW -- why is there an issue drafting PRs? That has nothing to do with "gaining consensus of the chair and group". In the very worst case, a PR doesn't get merged if it isn't approved.

What am I missing here?

**Comment by jacoscaz** [comment]
_/chair hat on_

> Please gain consensus of the chair and group.

As a group, we have not agreed on a formal process (yet). As the current chair, however, I would like participants to feel free to open PRs as they see fit, provided they accept that opening a PR doesn't mean that such PR will necessarily be approved. Opening a PR should not be subject to the group's or my own agreement. This is the same logic I've followed for https://github.com/w3c/WebID/pull/27 , which was ultimately rejected by the group but still proved quite useful for me personally as I try to figure out how to move the conversation forward in a productive manner.

**Comment by jacoscaz** [comment]
_/chair hat off_

I'm -1 on this as it complicates validation.

**Comment by csarven** [comment]
Can you elaborate on "complicates validation"?

Again, this is a note, an advisory, a consideration, a lower-case may or might or could or can ... It does not require something that needs to have a test case for the purpose of confirming an implementation's conformance for what would be required for interop.

**Comment by jacoscaz** [comment]
_/chair hat off_

@csarven insofar as a change is made WRT this topic, I would rather have the spec clearly indicate a minimal amount of triples that a profile document MUST consist of. Not only in examples but as normative content. The spec as-is doesn't mandate anything as far as the contents of the profile document and that is, to me, an issue that primarily affects validation. This note, to me, makes the current spec even less clear by making the examples less of a reference point. See discussion in #33 and #24 .

**Comment by woutermont** [comment]
> Can you elaborate on "complicates validation"?

If I may elaborate on that, @csarven, because I guess it is primarily my insistence on a mandatory predicate that got this discussion started.

With the current spec, if someone enters their WebID into an application, when the application dereferences it to its WebID Document, it faces the following problems:

1. The application has no way of nowing whether it actually retrieved a WebID Document, apart from the presumption that the user would not have entered some other URI.

2. Even if the application assumes it retreived a WebID Document, it has no way of knowing if it is actually the correct WebID Document of the user, unless it further assumes that neither the user nor the underlying technology has made a mistake (e.g. in setting up wrong redirects).

Now, **(1)** is nowadays conventionally solved by checking the Document for a statement indicating `foaf:PersonalProfileDocument` as the `rdf:type` of the Document's URL, and **(2)** is by checking for a `foaf:primaryTopic` statement relating the Document URL to the WebID. My suggestion was therefore to make these conventions requirements, so that applications can _actually_ rely on them to be present.

Broadening the possible predicates to do this makes it **less** reliable rather than more, that's what I have been trying to tell the group the whole time. This is not about someones preferences for one vocabulary over another, as some are framing it, but about the reliability of applications.^

---

_^ This is actually once more a perfect indication why the "web developer perspective" of @kidehen completely misses the point: hardly any developer will ever have to deal with those terms; a handful of people will write a few WebID libraries that perform those checks, and a few organisations providing WebIDs will write some code inserting those statements in every Document, and that's it. No need to hate on FOAF._

**Comment by melvincarvalho** [comment]
CGs operate on the principle they they:

> must be fair and must not unreasonably favor or discriminate against any group participant

This PR has been merged *directly* into this repo and hence has received disproportionate attention, both from a technical standpoint, and a process standpoint.  

It's a one of the reasons that a freeze is needed on ED WebID 1.0, and it's a use of privileges that is disruptive to the functioning of the group.

@csarven this can be easily resolved by redoing the PR from a fork of the repo.  As an experienced group member I am sure you appreciate the principle of fairness here, and a simple resolution.

**Comment by TallTed** [comment]
> [@melvincarvalho] It prevents me from adding a review in the top right section

I don't think what you're perceiving is actually what's happening.

See [GitHub docs, `about-pull-request-reviews`](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/about-pull-request-reviews) -- 

> After a pull request is opened, anyone with _read_ access can review and comment on the changes it proposes. You can also suggest specific changes to lines of code, which the author can apply directly from the pull request. For more information, see "[Reviewing proposed changes in a pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/reviewing-changes-in-pull-requests/reviewing-proposed-changes-in-a-pull-request)."

There is also this --

> By default, in public repositories, any user can submit reviews that approve or request changes to a pull request. Organization owners and repository admins can limit who is able to give approving pull request reviews or request changes. For more information, see "[Managing pull request reviews in your organization](https://docs.github.com/en/organizations/managing-organization-settings/managing-pull-request-reviews-in-your-organization)" and "[Managing pull request reviews in your repository](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/managing-repository-settings/managing-pull-request-reviews-in-your-repository)."

I do not *think* that the limits described in the latter paragraph have been imposed on this repository, but if they have, then they should probably be reverted to the defaults, until and unless spammish activity warrants re-imposition of such limits..

**Comment by jacoscaz** [comment]
_/chair hat on_

Closing this PR as it's unlikely to gather significant consensus on both technical and process grounds. This should be further discussed within existing issues or a dedicated one. Furthermore, now that we have settled on a process, please open PRs from forks rather than from within this repository (see [CONTRIBUTING.md](https://github.com/w3c/WebID/blob/main/CONTRIBUTING.md#issues)).

**Pull request closed without merging**
