### PR TITLE
feat: CONTRIBUTING.md based on current governance by lazy consensus

### PR DESCRIPTION
**Pull request by jacoscaz**
This PR, which depends on #47, populates the CONTRIBUTING.md with a description of how the group operates at the moment of writing this, i.e. by means of lazy consensus.

### CODE REVIEW

**Comment by jacoscaz** [comment]
> Looks good

Thanks!

> Minor: I'm not sure the `Conformance` section is needed for a single `you MUST be a member` - it changes the tone of what is otherwise a welcoming document, arguably needlessly.

@webr3 good point - done!

**Comment by melvincarvalho** [comment]
LGTM

**Comment by jacoscaz** [comment]
@jonassmedegaard thank you for catching that, I think you're right. Fixed.

**Comment by jacoscaz** [comment]
Merging this in based on:

- feedback on this specific PR
- feedback on https://github.com/w3c/WebID/pull/49, which builds upon this one
- the fact that this reflects the current state of the CG as-is

**Pull request merged**
