### PR TITLE
Init README

### PR DESCRIPTION
**Pull request by csarven**
Closes https://github.com/w3c/WebID/issues/18 https://github.com/w3c/WebID/issues/26

### CODE REVIEW

**Comment by melvincarvalho** [comment]
-1 too many bureaucratic dependencies, puts work at risk

This would require many months of debate and discussion to agree on all items.

A good README is a plus though

**Comment by jacoscaz** [comment]
Insofar as I can see, and please correct me if I am wrong, this PR only introduces one additional dependency (https://www.w3.org/Consortium/cepc/) on top of the ones that would be introduced by https://github.com/w3c/WebID/pull/31 .

However, https://github.com/w3c/WebID/pull/31 does introduce a significant number of dependencies and constraints which makes discussing the changes brought by these two PR separately a bit awkward as one cannot be merged without the other.

As chair, I would suggest closing these two PRs and opening a new one that includes the changes brought by both of them.

**Comment by csarven** [comment]
How about processing PR 31, and then this PR (30) ?

It is also possible to process both at the same time. This PR (30) merely references a CONTRIBUTING document. If the contents of CONTRIBUTING changes, it makes no difference to the README because we'd still want people to discover CONTRIBUTING.

**Comment by melvincarvalho** [comment]
> Perhaps consider adding an empty-ish CONTRIBUTING.md

I'm -0 on this. But it could be done, if it is lightweight and contains no possible gotchas.  Make it clear it's informative and has not had full group ratification.

**Comment by melvincarvalho** [comment]
> I agree to participate in the WebID Community Group under the terms of the [Community and Business Group Process](https://www.w3.org/community/about/process/). I agree to abide by the terms and spirit of the[ Code of Ethics and Professional Conduct](https://www.w3.org/Consortium/cepc/). I agree to participate as an individual under the [W3C Community Contributor License Agreement](https://www.w3.org/community/agreements/cla) ([summary](https://www.w3.org/community/about/agreements/summary/)). (Required)

If it's implicit, then we're already good.  That takes away any urgency.

**Review by TallTed — APPROVED** [review]
LGTM

**Comment by jacoscaz** [comment]
Closing as superseded by #47 .

**Pull request closed without merging**
